# Generated by Django 4.2.1 on 2023-05-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.IntegerField()),
                ('User_name', models.TextField()),
                ('User_password', models.TextField()),
                ('Is_admin', models.IntegerField()),
            ],
        ),
    ]
