# Generated by Django 4.2.1 on 2023-05-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_user_id_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Is_login',
            field=models.IntegerField(default=0),
        ),
    ]
